site_name: Мой путь в Python
theme:
  name: dracula
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: indigo
  font:
    text: Roboto
    code: Fira Code
nav:
  - Главная: index.md
  - Обо мне: about.md
  - Проекты: projects.md
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true